# Generated by Django 3.2.7 on 2021-09-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_settings', '0002_about_aboutphoto_home_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
