# Generated by Django 3.2.7 on 2021-09-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_settings', '0003_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
    ]
