# Generated by Django 3.2.7 on 2021-09-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_settings', '0004_alter_home_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Link'},
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='my_settings.project')),
            ],
        ),
    ]
